notifications:
  email: false

#language: python
language: generic

os:
  - linux
  - osx
  - windows

python:
  #- "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

before_install:
  - which python3
  #- export VERSIONER_PYTHON_PREFER_32_BIT=yes
  - python3 --version
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python3; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH="/c/Python37:/c/Python37/Scripts:$PATH"; fi

# command to install dependencies
install:
  - python3 -m pip install --upgrade pip --user
  - pip3 install -r requirements.txt
  - pip3 install pyinstaller
# command to run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash plenopticam/script/bundling/pyinst2app.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash plenopticam/script/bundling/py2bin.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then bash plenopticam/script/bundling/py2exe.bat; fi
  - sleep 1
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then dist/plenopticam.app; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then dist/plenopticam.app; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dist/plenopticam.app; fi