notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        -  python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - plenopticam -h
  # trigger unit tests
  - python3 test/unit_test.py || python test/unit_test.py
  - sleep 1

before_deploy:
  - pip3 install pyinstaller
  # osx bundling
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        npm install --global create-dmg;
        bash plenopticam/scripts/bundling/pyinst2app.sh;
        sleep 1;
        open dist/plenopticam.app;
    fi
  # linux bundling
  - if [ "$TRAVIS_OS_NAME" = "xenial" ]; then
        bash pypi_automation.sh;
        bash plenopticam/scripts/bundling/py2bin.sh;
        sleep 1;
        dist/plenopticam.app;
    fi
  # win bundling
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        python -m pip install pywin32
        plenopticam/scripts/bundling/py2exe.bat;
        python --version;
        dist/plenopticam.exe;
        python --version;
    fi

# open release draft on GitHub
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file:
    - /Users/travis/build/hahnec/plenoprivate/dist/plenopticam_0.3.5.dmg
    - /home/travis/build/hahnec/plenoprivate/dist/plenopticam_0.3.5.tar.gz
    - C:\Users\travis\build\hahnec\plenoprivate\dist\plenopticam.exe
  skip_cleanup: true
  draft: true
  on:
    tags: true
  name: PlenoptiCam $TRAVIS_TAG