notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - choco install advanced-installer
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - plenopticam -h
  # trigger unit tests
  - python3 -m test.unit_test || python -m test.unit_test

#before_deploy:
  - pip3 install pyinstaller
  # osx bundling
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        npm install --global create-dmg;
        bash plenopticam/scripts/bundling/pyinst2app.sh;
        sleep 1;
        open dist/plenopticam.app;
        export RELEASE_PKG_FILE=$(ls dist/*.dmg);
    fi
  # linux bundling (with wheel upload to pypi)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        bash plenopticam/scripts/bundling/py2bin.sh;
        dist/plenopticam;
        export RELEASE_PKG_FILE=$(ls dist/*.tar.gz);
    fi
  # win bundling
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        pip3 install pypiwin32;
        pip3 install pyinstaller --upgrade;
        plenopticam/scripts/bundling/py2exe.bat;
        sleep 1;
        plenopticam/scripts/bundling/msi_auto-gen.bat;
        export RELEASE_PKG_FILE=$(ls dist/*.msi);
    fi

before_deploy:
  #bash plenopticam/scripts/bundling/pypi_automation.sh;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        pip3 install --upgrade twine;
        python3 setup.py sdist bdist_wheel;
        python3 -m twine upload --repository https://test.pypi.org/legacy/ dist/* -u __token__ -p $TEST_PYPI;
        python3 -m pip install --index-url https://test.pypi.org/legacy/ plenopticam;
    fi
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

# open release draft on GitHub
deploy:
  - provider: releases
    name: PlenoptiCam $TRAVIS_TAG
    skip_cleanup: true
    api_key:
      secure: HpkQsqXHzAd62Hc1f/eMdcRzluQo4cS44q8WbMrUTxMFjGQ822JPsO/s7uTZAs5FZZzE/cPUTyYU2c8Rmn9tg547v3D5Dy16eG5jr8dJqGKkwN3vggv4x7U8PiajAIhbmWRqde7ywduqq98kcipTXaATrCtYvCIfRb7H08qmozV5L30DYdICvTlgFVXu6wq/TzQsCqG2XzXiVyvlTq/JVnC+Tl2Kl/33sDa9kJoaQbib4yNZlx5zWTOydkQQvTvK3O9HvHF5ZpWiSxbrg70C6zFQKscpmcpGth/FJEWoQxZvO91jUWBU1Thl5RgrQIZlSQFGfoVioTamCKy219ytlbgpmxvyZzeO4FirNoJ5xDKWy2HfY9JQJVt2cMi1kbniRfw3nSZRig7pGjg07eamvb38a5FWWyQe7gt/Obcbf0lyAQQVeo9HiktETRX8tAnfJjxv2qrLoYUuH0n27XZP+CJfLK35j6ptoYeesmyiZgYSYt2M7exhMP1UX+ts977nnmf7/JZIOg/Ytm4+Ba4FzIyvGPizKTSYyGmcLYYoW0LIdYkAO/mr/PSvrjdt6p9dZcNAKBMufrgwAuH3tyQgS+pAO8h4GFwfG8OrBR/eoBBJf5QaZj/YvZwWLj55bGr6+g4KSS3JVeFvx2xCLKs640gVtoQQF/682IYuGGU3J2g=
    file:
      - "${RELEASE_PKG_FILE}"
    draft: true
    on:
      repo: hahnec/plenoprivate
#    tags: true
#    branches:
#      only:
#        - develop
#        - master

  - provider: pypi
    skip_existing: true
    skip_cleanup: true
    server: https://upload.pypi.org/legacy/
    user: __token__
    password:
      secure: BUeNcM5jZixQ+1fjKmXmPY97lAEtr2NZNVm8SmyJUoaMWXGoO+qGKb9Fy8aVVIT7qvYRZKiGuTaoOb9VuVSTq7spRAmPXKXQbXMybbWPszapCKxmxVse7ADZEq3zQJ4vulmMtqzFwYlLgyNo4OnbVSGBwPe8jA8QeMSXCsAqKoJZW414yvd62g/qFfXVcNz7nL/oFIxPSzWezrXHWbbIfpf14H4rD6dJ95dyqMqzPr0W4OpKN5Q7vSpg9EwDggP3ypwoXbS2cPkQjIpt4UviFdyIAbJ7/Kofqhomfi1V9WRY0xpAJL7lPkMnsEpTSu8jACIyH6Trvs3o1+eS1V/RuR3+nUl5sX0eZSFcS+PF9Qce+r32f3BahhH+x6innrQ3idSQh/N77FFz0WdLIVW6iJ8ziyzrP3CSEzPUCLDUTQwyI1fJ9jDmAXIRCwm6VyaqrcTvekBtjsurZ+dIahuDzdNCz1Zl9Pq6mxtUjMoIE4rY7rjACXgbtkSWHsUvByFl4RTurkD14fVOun3Gu7QauXtOxg25PrF+bvVqNeei6spMQbTRXutUqTKJI16m+0/hUAyJuD6NPaQp++2+sPBJ2c4/GtBY+2W9pOj+9WX5ckuCcgmj+2asdxz8lO60MtZ7Zr8v2eW8i3l0u63ahQ4YxHsaNTvXRkUaOZoub08FogE=
    on:
      condition: $TRAVIS_OS_NAME = linux