notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      mkdir dl;
      curl -SfL "http://wp12283669.server-he.de/Xchange/advinst.msi" -o ./dl/advinst.msi;
      ls dl;
      msiexec /i "./dl/advinst.msi" APPDIR="./dl/" /qn -lv ./dl/log.txt;
    fi

# commands to run tests
script:
  # open app from CLI
  - plenopticam -h
  # trigger unit tests
  #- python3 test/unit_test.py || python test/unit_test.py
  - sleep 1

#before_deploy:
  - pip3 install pyinstaller
  # osx bundling
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        npm install --global create-dmg;
        bash plenopticam/scripts/bundling/pyinst2app.sh;
        sleep 1;
        open dist/plenopticam.app;
    fi
  # linux bundling (with wheel upload to pypi)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        bash plenopticam/scripts/bundling/pypi_automation.sh;
        bash plenopticam/scripts/bundling/py2bin.sh;
        sleep 1;
        ls dist;
        dist/plenopticam;
    fi
  # win bundling
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        pip3 install pypiwin32;
        plenopticam/scripts/bundling/py2exe.bat;
        sleep 1;
        ls dist/plenopticam;
        sleep 1;
        compact /c /s:"dist/plenopticam";
    fi
    #Compress-Archive -Path dist/plenopticam -CompressionLevel Optimal -DestinationPath dist/plenopticam.zip -Force > nul;
    #dist/plenopticam/plenopticam.exe;
    #pip3 install pywin32;
# https://www.advancedinstaller.com/forums/viewtopic.php?t=31973
# C:\ProgramData\Caphyon\Advanced Installer

# open release draft on GitHub
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: D13p76AjmWYGFgV+xndTrhgC7TPZ0rL/i83KLwXUswqVbYAragJDVdjIMqYyhnjJbnwuiJzBK/jiHwcuuBDl/aaoSebjY6UQQrdiHkrgSun9FkJsAaAhEmH5dZRokQxMHBk3Z82SSaqv8+KtoisAoNfHun5vWUtbWK4YMjegSIFLBWVmoLyC9uYji0fBb+IF/AICdiAb5fqWDVIFBgt0qo0UJ6CacINb+vaTHani5mjig07WCAb1b/2W9ef1y434cJNXql7sxUbvZDiCKW0fXtZFo0WGNPyCFauqt+3tT8uGf+sYbllMFBZnheim+mxqSq5L7Emv96ayJk7ewIJqIyHdBkeI55rmxDyzoFEd5KD1yFwiuAcNcHlhrCiV6FTVy0QaWuELFFdyDVuKYjubBEEnLZAlZv4kWfdtpaiPYWYzUlqPQZBj/UqqIkBPL6fMnON1HsuPslcSM83ws7HqA674vKGr3qHI6HSmLvGmQnZ5hpUTC1/XfypKshzZ2QhQGrP8qNzX2+MSDaIf3g9V+834otJhXOUNQxVy4tR/9O1JRLi4wyYqmN0Qrcb+hK6TU54RUACqp4tZ5OfadCGONBRmDWRPl2GpIhW51BXGiQAe9ilzHLd4glV0/jaLNk6Y6VH64H58FP8hGvCn9n3Iug9PTiB5Ww4W6LRSNP+F858=
  file_glob: true
  file:
    - /Users/travis/build/hahnec/plenoprivate/dist/plenopticam_0.3.5.dmg
    - /home/travis/build/hahnec/plenoprivate/dist/plenopticam_0.3.5.tar.gz
    - C:\Users\travis\build\hahnec\plenoprivate\dist\plenopticam.zip
  draft: true
  on:
#    tags: true
    repo: hahnec/plenoprivate
  name: PlenoptiCam $TRAVIS_TAG

  deploy:
    provider: pypi
    skip_existing: true
    skip_cleanup: true
    server: https://testpypi.python.org/pypi
    user: hahnec
    password:
      secure: WvUIg6H5cXTrbii42b8krKprrMB9MgXgHX64Da18pQrKG7ByjB4tSZmD7pxpab2OFlFV3b9bMRxaFuTxwIfM00aQ8LnV5Km2oSNOMC75qvjsjvLsfT/TS0RnZ9vq+p0rs5NmPMgdqXz4JdQ8iC0pnKYZhUsMCa7YAVGcPAt9XmQZeDZ46SOiqAVpwaPFJj+OJT+dc0jmIfnrYO2jNH3lRTTNM711fBLONhoXUUdgpIS4CpuKiGBD6AbeU7JkzivKPeZ+t7wt/WZfhR1a3Uwva7pV+EBJAueMBNHyABnO3KHsSGGGbZZ8ORTrCIS7r8fVMPmledk3IO4D8kurhfROcYySzkpTPNgdO7Y6QHq0EgOV9SHan8svHm19GyJJeWpFrus6v8g9NeNZa9h6OiLMEX5m6kxo4TCQnEq80nvHRchSNIE9s2m4RiMiikZFoabhQyVhHTKV/298Lbdbf3FFBe8xH4+/nz6/k2Lp008Yhc4wQSEbHyxhh4m4sh2wPoWSceYITtmCoawVUzCMLSfNTGVmQduvCYX4a+SIh1omlApkCqqKMlNAlL3PYd4UxJlybS//AB+58eH52lMxWKFIpfoLsUEyfEu/mWltncNc/TxVL2gTfX0w1utr/5dqBzQD0O8h1p9GdqBrnV5RWPp2ql9sfNioqxI5dgEIP8NYoro=
