notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - choco install advanced-installer
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - plenopticam -h
  # trigger unit tests
  - python3 test/unit_test.py || python test/unit_test.py

#before_deploy:
  - pip3 install pyinstaller
  # osx bundling
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        npm install --global create-dmg;
        bash plenopticam/scripts/bundling/pyinst2app.sh;
        sleep 1;
        open dist/plenopticam.app;
    fi
  # linux bundling (with wheel upload to pypi)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        bash plenopticam/scripts/bundling/py2bin.sh;
        dist/plenopticam;
    fi
  # win bundling
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        pip3 install pypiwin32;
        pip3 install pyinstaller --upgrade;
        plenopticam/scripts/bundling/py2exe.bat;
        sleep 1;
        plenopticam/scripts/bundling/msi_auto-gen.bat;
    fi

# open release draft on GitHub
deploy:
  provider: releases
  name: PlenoptiCam $TRAVIS_TAG
  skip_cleanup: true
  api_key:
    secure: HpkQsqXHzAd62Hc1f/eMdcRzluQo4cS44q8WbMrUTxMFjGQ822JPsO/s7uTZAs5FZZzE/cPUTyYU2c8Rmn9tg547v3D5Dy16eG5jr8dJqGKkwN3vggv4x7U8PiajAIhbmWRqde7ywduqq98kcipTXaATrCtYvCIfRb7H08qmozV5L30DYdICvTlgFVXu6wq/TzQsCqG2XzXiVyvlTq/JVnC+Tl2Kl/33sDa9kJoaQbib4yNZlx5zWTOydkQQvTvK3O9HvHF5ZpWiSxbrg70C6zFQKscpmcpGth/FJEWoQxZvO91jUWBU1Thl5RgrQIZlSQFGfoVioTamCKy219ytlbgpmxvyZzeO4FirNoJ5xDKWy2HfY9JQJVt2cMi1kbniRfw3nSZRig7pGjg07eamvb38a5FWWyQe7gt/Obcbf0lyAQQVeo9HiktETRX8tAnfJjxv2qrLoYUuH0n27XZP+CJfLK35j6ptoYeesmyiZgYSYt2M7exhMP1UX+ts977nnmf7/JZIOg/Ytm4+Ba4FzIyvGPizKTSYyGmcLYYoW0LIdYkAO/mr/PSvrjdt6p9dZcNAKBMufrgwAuH3tyQgS+pAO8h4GFwfG8OrBR/eoBBJf5QaZj/YvZwWLj55bGr6+g4KSS3JVeFvx2xCLKs640gVtoQQF/682IYuGGU3J2g=
  file_glob: true
  file:
    - /Users/travis/build/hahnec/plenoprivate/dist/plenopticam_*.dmg
    - /home/travis/build/hahnec/plenoprivate/dist/plenopticam_*.tar.gz
    - C:\Users\travis\build\hahnec\plenoprivate\dist\plenopticam_*.msi
  draft: true
  on:
    repo: hahnec/plenoprivate
#    tags: true
#    branches:
#      only:
#        - develop
#        - master

#  deploy:
#    provider: pypi
#    skip_existing: true
#    skip_cleanup: true
#    se  rver: https://testpypi.python.org/pypi
#    user: hahnec
#    password:
#      secure: WvUIg6H5cXTrb#ii42b8krKprrMB9MgXgHX64Da18pQrKG7ByjB4tSZmD7pxpab2OFlFV3b9bMRxaFuTxwIfM00aQ8LnV5Km2oSNOMC75qvjsjvLsfT/TS0RnZ9vq+p0rs5NmPMgdqXz4JdQ8iC0pnKYZhUsMCa7YAVGcPAt9XmQZeDZ46SOiqAVpwaPFJj+OJT+dc0jmIfnrYO2jNH3lRTTNM711fBLONhoXUUdgpIS4CpuKiGBD6AbeU7JkzivKPeZ+t7wt/WZfhR1a3Uwva7pV+EBJAueMBNHyABnO3KHsSGGGbZZ8ORTrCIS7r8fVMPmledk3IO4D8kurhfROcYySzkpTPNgdO7Y6QHq0EgOV9SHan8svHm19GyJJeWpFrus6v8g9NeNZa9h6OiLMEX5m6kxo4TCQnEq80nvHRchSNIE9s2m4RiMiikZFoabhQyVhHTKV/298Lbdbf3FFBe8xH4+/nz6/k2Lp008Yhc4wQSEbHyxhh4m4sh2wPoWSceYITtmCoawVUzCMLSfNTGVmQduvCYX4a+SIh1omlApkCqqKMlNAlL3PYd4UxJlybS//AB+58eH52lMxWKFIpfoLsUEyfEu/mWltncNc/TxVL2gTfX0w1utr/5dqBzQD0O8h1p9GdqBrnV5RWPp2ql9sfNioqxI5dgEIP8NYoro=

after_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      plenopticam/scripts/bundling/pypi_automation.sh;
    fi