notifications:
  email: false

#language: python
language: generic

os:
  - linux
  - osx
  - windows

python:
  #- "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

before_install:
  - which python
  #- brew install python --universal --framework
  #- brew install wget
  #- which python
  - export VERSIONER_PYTHON_PREFER_32_BIT=yes
  #- defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
  #- which python
  - python --version
  # https://github.com/Homebrew/homebrew/issues/34470
  #- arch -i386 brew install wxpython --universal
  #- mkdir dl
  #- cd dl
  #- wget http://downloads.sourceforge.net/wxpython/wxPython3.0-osx-3.0.2.0-cocoa-py2.7.dmg
  #- ls
  #- cd ..
  #- sudo ./packages.sh
  #- arch -i386 python -c "import wx; print wx.__version__"
 # - arch -i386 pip install pyinstaller
  #- arch -i386 pyinstaller --noconsole --onefile hw.py
  #- ls
  #- hdiutil create dist/hw.dmg -srcfolder dist/ -ov
  #- zip -r dist/hw.zip dist/hw.app
  #- ls dist/

# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pyinstaller
# command to run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash plenopticam/script/bundling/pyinst2app.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash plenopticam/script/bundling/py2bin.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then bash plenopticam/script/bundling/py2exe.bat; fi
  - sleep 1
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then dist/plenopticam.app; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then dist/plenopticam.app; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dist/plenopticam.app; fi