notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - choco install advanced-installer
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - plenopticam -h
  # trigger unit tests
  #- python3 -m test.unit_test || python -m test.unit_test

#before_deploy:
  - pip3 install pyinstaller
  # osx bundling
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        npm install --global create-dmg;
        bash plenopticam/scripts/bundling/pyinst2app.sh;
        sleep 1;
        open dist/plenopticam.app;
    fi
  # linux bundling (with wheel upload to pypi)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        bash plenopticam/scripts/bundling/py2bin.sh;
        dist/plenopticam;
    fi
  # win bundling
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        pip3 install pypiwin32;
        pip3 install pyinstaller --upgrade;
        plenopticam/scripts/bundling/py2exe.bat;
        sleep 1;
        plenopticam/scripts/bundling/msi_auto-gen.bat;
        sleep 1;
        ls dist;
    fi

before_deploy:
  #bash plenopticam/scripts/bundling/pypi_automation.sh;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        pip3 install --upgrade twine;
        python3 setup.py sdist bdist_wheel;
        python3 -m twine upload --repository https://test.pypi.org/legacy/ dist/* -u __token__ -p $TEST_PYPI;
        python3 -m pip install --index-url https://test.pypi.org/legacy/ plenopticam;
    fi

# open release draft on GitHub
deploy:
  - provider: releases
    name: PlenoptiCam $TRAVIS_TAG
    skip_cleanup: true
    api_key:
      secure: HpkQsqXHzAd62Hc1f/eMdcRzluQo4cS44q8WbMrUTxMFjGQ822JPsO/s7uTZAs5FZZzE/cPUTyYU2c8Rmn9tg547v3D5Dy16eG5jr8dJqGKkwN3vggv4x7U8PiajAIhbmWRqde7ywduqq98kcipTXaATrCtYvCIfRb7H08qmozV5L30DYdICvTlgFVXu6wq/TzQsCqG2XzXiVyvlTq/JVnC+Tl2Kl/33sDa9kJoaQbib4yNZlx5zWTOydkQQvTvK3O9HvHF5ZpWiSxbrg70C6zFQKscpmcpGth/FJEWoQxZvO91jUWBU1Thl5RgrQIZlSQFGfoVioTamCKy219ytlbgpmxvyZzeO4FirNoJ5xDKWy2HfY9JQJVt2cMi1kbniRfw3nSZRig7pGjg07eamvb38a5FWWyQe7gt/Obcbf0lyAQQVeo9HiktETRX8tAnfJjxv2qrLoYUuH0n27XZP+CJfLK35j6ptoYeesmyiZgYSYt2M7exhMP1UX+ts977nnmf7/JZIOg/Ytm4+Ba4FzIyvGPizKTSYyGmcLYYoW0LIdYkAO/mr/PSvrjdt6p9dZcNAKBMufrgwAuH3tyQgS+pAO8h4GFwfG8OrBR/eoBBJf5QaZj/YvZwWLj55bGr6+g4KSS3JVeFvx2xCLKs640gVtoQQF/682IYuGGU3J2g=
    file_glob: true
    file:
      - /Users/travis/build/hahnec/plenoprivate/dist/plenopticam_*.dmg
      - /home/travis/build/hahnec/plenoprivate/dist/plenopticam_*.tar.gz
      - C:\Users\travis\build\hahnec\plenoprivate\dist\plenopticam_*.msi
    draft: true
    on:
      repo: hahnec/plenoprivate
#    tags: true
#    branches:
#      only:
#        - develop
#        - master

  - provider: pypi
    skip_existing: true
    skip_cleanup: true
    server: https://upload.pypi.org/legacy/
    user: __token__
    password:
      secure: joSfCl33XmE6P0DZjtRRn/ZRBNfyTO3Ibd1aULWXSdfA9STJswxVR5THl/X4pKOFHSU+3LBVOO9+zjJgC3M+Nr9TrsI365+kdmD+0tOQ47rt9N+2H4/FuXdOj0EL07eF73LGbvfhTBtdFd0hW8UFL3lWJLdLOUxRUX+OWgRtx5vusLu+No8Zy6aje7oTo8kdGEy47XzjYwXhXTNrvxXeQPasjaKUtfmpb6f/J8ozsW/H/Ok2VgqPCakKiqPknXzE0SMcb+nd0otix3x6VKci2vvlTF8sDq9CF3hyFPKvuIvTzrhESQwvGFDk9Tt3AEa9MqXxrswPyM5i6bvB8YI/kV/vmA22MyglziVsU4Gf7u+S7gYTHliWsyOaiWm8dTpJU5ApR4yfSoBUPxNMBybfOpzaiCflOIy/QFcDzGPRKRsNDl9vvvMvpdcwU65djeaeuNnR7bVbsox4dq5/l+N+p86X3Fm9Odo/M77Qs1KtjUD3vjMf/ku2mEEn3WL4GrLgpyvt5PaWaeRqQT1twT20XCGiI9tZcybsAvYH1KyXTfwz5t6+xVJ4Ccyr/6cdamwwogzuNNLyWkpGhRdqMyRYUQQPfkNWQEzr1xyPAU3QPjZ822YgEBVl3kSixR0JOg0Q25Tv0juRom4pTZK1yA21yMyYa9caJlh7zWg1A6n6/js=
    on:
      condition: $TRAVIS_OS_NAME = linux