notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - pip3 install pyinstaller
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  - python3 test/unit_test.py || python test/unit_test.py
  - sleep 1
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        npm install --global create-dmg;
        bash plenopticam/scripts/bundling/pyinst2app.sh;
        sleep 1;
        dist/plenopticam.app;
    fi
  - if [ "$TRAVIS_OS_NAME" = "xenial" ]; then
        bash plenopticam/scripts/bundling/py2bin.sh;
        sleep 1;
        dist/plenopticam.app;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        plenopticam/scripts/bundling/py2exe.bat;
        sleep 1;
        dist/plenopticam.exe;
    fi